default: &default
  db: &db
    username: "${db_username}"
    password: "${db_password}"

dev: &dev
  <<: *default

test: &test
  <<: *default
  db:
    <<: *db
    username: testUser
    password: testPassword

prod: &prod
  <<: *default
