default: &default
  db: &db
    username: "${db_username}"
    password: "${db_password}"
  jwt: &jwt
    key: "${jwt_key}"

dev: &dev
  <<: *default

test: &test
  <<: *default
  db:
    <<: *db
    username: testUser
    password: testPassword
  jwt:
    <<: *jwt
    key: "test"

prod: &prod
  <<: *default
