default: &default
  avionics_dash: &avionics_dash
    db_name: avionics_dash_dev
    collections:
      users: users
      modules: modules
      courses: courses
      assignments: assignments
    host: localhost
    port: 27017
    auth_mechanism: "SCRAM-SHA-256"

dev: &dev
  <<: *default

test: &test
  <<: *default
  avionics_dash:
    <<: *avionics_dash
    db_name: avionics_dash_test

prod: &prod
  <<: *default
  avionics_dash:
    <<: *avionics_dash
    db_name: avionics_dash
    connection_string: "mongodb+srv://prodUser:${password}@cluster0.olfdyj9.mongodb.net/?retryWrites=true&w=majority"
